### ISSUE TITLE
最終課題（フリマアプリ）提出

### ISSUE THREAD

**Issue by kamiyama0304** [vixer93/freemarket_sample_68b#41]
■ URL
IPアドレス：52.196.162.19
Github（最終課題のリポジトリ）：vixer93/freemarket_sample_68b

■ Basic認証
ID：admin
Pass：2222

■ テスト用アカウント
◯ 購入者用
メールアドレス：w@w.com
パスワード：aaaaaaa

◯ 購入用カード情報
番号：4242424242424242
期限：2020/03
セキュリティカード：123

◯ 出品者用
メールアドレス：a@a.com
パスワード：aaaaaaa

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
IPアドレスにアクセスすると、応答時間が長く下記のエラーとなってしまう。
[![Image from Gyazo](https://i.gyazo.com/75d1ffa0622190136f5cb51b10f4b8ee.png)](https://gyazo.com/75d1ffa0622190136f5cb51b10f4b8ee)

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by kyo-today** [comment]
IPアドレス：52.198.162.19
こちらが正しいIDになります

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①写真無しで出品しようとすると、出品はできないがエラーになってしまう。**
[![Screenshot from Gyazo](https://gyazo.com/e5eabde5b759d4da5776dc188c9585a9/raw)](https://gyazo.com/e5eabde5b759d4da5776dc188c9585a9)

**②出品ボタンを押すとエラーになってしまう**
[![Screenshot from Gyazo](https://gyazo.com/336aeb4d20a5c0cf14e83c8b89baba07/raw)](https://gyazo.com/336aeb4d20a5c0cf14e83c8b89baba07)

**③エラーの後ホームに戻ろうとすると、エラーになってしまう**
[![Screenshot from Gyazo](https://gyazo.com/2b1e25c47eed07ea07069577967c6ee1/raw)](https://gyazo.com/2b1e25c47eed07ea07069577967c6ee1)

**他の項目もチェックが出来ないため、次回ご提出時に商品出品以降の挙動を確認いたします！**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by keisukekodama** [comment]
修正ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
